# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demo-cui-addressupdating"
client_id = "563b9793f58be9eab5133301b7cf310f"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "mm-demo-seaaddress-00.myshopify.com"
